apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-depl
  annotations:
    argocd-image-updater.argoproj.io/image-list: collection=zhamburglar/mtg-tracker-collection
    argocd-image-updater.argoproj.io/auth.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collection
  template:
    metadata:
      labels:
        app: collection
    spec:
      containers:
        - name: collection
          image: zhamburglar/mtg-tracker-collection:latest
          imagePullPolicy: Always
          env:
            - name: NATS_URL
              value: "nats://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "mtg-tracker"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: collection-srv
spec:
  selector:
    app: collection
  ports:
    - name: collection
      protocol: TCP
      port: 3000
      targetPort: 3000
