apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-depl
  annotations:
    argocd-image-updater.argoproj.io/image-list: listing=zhamburglar/mtg-tracker-listing
    argocd-image-updater.argoproj.io/auth.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listing
  template:
    metadata:
      labels:
        app: listing
    spec:
      containers:
        - name: listing
          image: zhamburglar/mtg-tracker-listing:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: NATS_URL
              value: "nats://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "mtg-tracker"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: listing-srv
spec:
  selector:
    app: listing
  ports:
    - name: listing
      protocol: TCP
      port: 3000
      targetPort: 3000
