apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mtg-tracker-ingress-service
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "local-ca-issuer"
    traefik.ingress.kubernetes.io/router.middlewares: default-cors@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mtg-tracker.local
      secretName: mtg-tracker-tls
  rules:
    - host: mtg-tracker.local
      http:
        paths:
          - path: /api/users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/bulk(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: bulk-srv
                port:
                  number: 3000
          - path: /api/search(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: search-srv
                port:
                  number: 3000
          - path: /api/collection(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: collection-srv
                port:
                  number: 3000
          - path: /api/listing(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: listing-srv
                port:
                  number: 3000
          - path: /nats(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nats-srv
                port:
                  number: 8222
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 3000