name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'mtg-tracker-client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets.DOCKER_PASSWORD exists
        run: |
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "The secret 'DOCKER_PASSWORD' has not been made. Please go to 'settings > secrets > actions' to create it."
            exit 1
          fi
      - uses: actions/checkout@v2
      - run: cd mtg-tracker-client && docker build -t zhamburglar/mtg-tracker-client .
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push zhamburglar/mtg-tracker-client
