name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - 'mtg-tracker-client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secrets.DOCKER_PASSWORD exists
        run: |
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "The secret 'DOCKER_PASSWORD' has not been made. Please go to 'settings > secrets > actions' to create it."
            exit 1
          fi

      - uses: actions/checkout@v4

      # Enable Buildx for multi-arch builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push with caching
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./mtg-tracker-client
          push: true
          tags: zhamburglar/mtg-tracker-client:latest
          platforms: linux/arm64
          cache-from: type=registry,ref=zhamburglar/mtg-tracker-client:buildcache
          cache-to: type=registry,ref=zhamburglar/mtg-tracker-client:buildcache,mode=max
