name: tests-collection

on:
  pull_request:
    paths:
      - 'collection/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd collection && npm install && npm run test:ci
