name: tests-bulk

on:
  pull_request:
    paths:
      - 'bulk/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd bulk && npm install && npm run test:ci
