name: tests-search

on:
  pull_request:
    paths:
      - 'search/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd search && npm install && npm run test:ci
